package me.supercube.system.app.user.model;
// Generated 2016-9-13 11:32:38 by Hibernate Tools 4.3.1.Final


import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.datatype.jsr310.ser.LocalDateTimeSerializer;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.time.LocalDateTime;

/**
 * LoginLog generated by hbm2java
 */
@Entity
@Table(name = "loginlog")
public class LoginLog implements java.io.Serializable {

	private long loginlogid;//唯一标识
	private String userid;//用户
	private String name;//全名
	private LocalDateTime attemptdate;//尝试日期,尝试登录时的时间戳记
	private String attemptresult;//尝试结果,登录尝试的结果。有效值为“成功”、“失败”、“注销”或“超时”。
	private String adminuserid;//管理用户,当管理用户使另外一位用户注销时，这是管理用户的用户标识。
	private String sessionuid;//会话标识,与该活动相关联的会话标识。
	private String loginid;//登录标识,对成功或不成功的验证尝试所输入的登录标识。
	private String clienthost;//客户端主机,用户客户端（远程主机）的主机名。
	private Integer currentcount;//当前会话计数,截止此尝试日期的活动会话的计数。该计数包括系统中的所有会话，而不仅仅是此用户标识的会话。
	private String clientaddr;//客户端地址,用户客户端的 IP 地址（远程地址）。
	private String servername;//服务器,Server 名称
	private String serverhost;//服务器主机,该会话的 Server 的主机名或 IP 地址

	private String userType; //用户类型

	public LoginLog() {
	}

	public LoginLog(LocalDateTime attemptdate, String attemptresult) {
		this.attemptdate = attemptdate;
		this.attemptresult = attemptresult;
	}

	public LoginLog(String userid, String name, LocalDateTime attemptdate, String attemptresult, String adminuserid,
                    String sessionuid, String loginid, String clienthost, Integer currentcount, String clientaddr,
                    String servername, String serverhost) {
		this.userid = userid;
		this.name = name;
		this.attemptdate = attemptdate;
		this.attemptresult = attemptresult;
		this.adminuserid = adminuserid;
		this.sessionuid = sessionuid;
		this.loginid = loginid;
		this.clienthost = clienthost;
		this.currentcount = currentcount;
		this.clientaddr = clientaddr;
		this.servername = servername;
		this.serverhost = serverhost;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "loginlogid", unique = true, nullable = false)
	public Long getLoginlogid() {
		return this.loginlogid;
	}

	public void setLoginlogid(Long loginlogid) {
		this.loginlogid = loginlogid;
	}

	@Column(name = "userid", length = 30)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "name", length = 62)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@JsonSerialize(using = LocalDateTimeSerializer.class)
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@Column(name = "attemptdate", nullable = false, length = 19)
	public LocalDateTime getAttemptdate() {
		return this.attemptdate;
	}

	public void setAttemptdate(LocalDateTime attemptdate) {
		this.attemptdate = attemptdate;
	}

	@Column(name = "attemptresult", nullable = false, length = 15)
	public String getAttemptresult() {
		return this.attemptresult;
	}

	public void setAttemptresult(String attemptresult) {
		this.attemptresult = attemptresult;
	}

	@Column(name = "adminuserid", length = 30)
	public String getAdminuserid() {
		return this.adminuserid;
	}

	public void setAdminuserid(String adminuserid) {
		this.adminuserid = adminuserid;
	}

	@Column(name = "sessionuid", length = 36)
	public String getSessionuid() {
		return this.sessionuid;
	}

	public void setSessionuid(String sessionuid) {
		this.sessionuid = sessionuid;
	}

	@Column(name = "loginid", length = 50)
	public String getLoginid() {
		return this.loginid;
	}

	public void setLoginid(String loginid) {
		this.loginid = loginid;
	}

	@Column(name = "clienthost", length = 100)
	public String getClienthost() {
		return this.clienthost;
	}

	public void setClienthost(String clienthost) {
		this.clienthost = clienthost;
	}

	@Column(name = "currentcount")
	public Integer getCurrentcount() {
		return this.currentcount;
	}

	public void setCurrentcount(Integer currentcount) {
		this.currentcount = currentcount;
	}

	@Column(name = "clientaddr", length = 100)
	public String getClientaddr() {
		return this.clientaddr;
	}

	public void setClientaddr(String clientaddr) {
		this.clientaddr = clientaddr;
	}

	@Column(name = "servername", length = 100)
	public String getServername() {
		return this.servername;
	}

	public void setServername(String servername) {
		this.servername = servername;
	}

	@Column(name = "serverhost", length = 100)
	public String getServerhost() {
		return this.serverhost;
	}

	public void setServerhost(String serverhost) {
		this.serverhost = serverhost;
	}

	@Column(name = "userType", length = 100)
	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}
}
